<?php $this->layout('system::layout/default', [
    'title'      => __('Documentation'),
    'page_title' => __('Documentation'),
]) ?>
<div class="row">
    <div class="m-sm-auto m-md-auto m-lg-0 col-sm-8 col-md-8 col-lg-7 col-xl-10">
        <div class="card shadow border-0 border-radius-12">

            <form action="?add" method="post">
                <div class="card-body">
                    <h4 class="card-title"><?= __('Adding an article') ?></h4>

                    <div class="form-group">
                        <label for="article_name"><?= __('Enter an article name') ?></label>
                        <input type="text"
                               class="form-control <?= (isset($error['article_name']) ? 'is-invalid' : '') ?>"
                               name="article_name"
                               id="article_name"
                               required
                               placeholder="<?= __('Article name') ?>"
                        >
                    </div>
                    <div class="form-group">
                        <label for="article_description"><?= __('Enter article description') ?></label>
                        <input type="text"
                               class="form-control <?= (isset($error['article_description']) ? 'is-invalid' : '') ?>"
                               name="article_description"
                               id="article_description"
                               required
                               placeholder="<?= __('Article description') ?>"
                        >
                    </div>
                    <div class="form-group">
                        <label for="cms_version"><?= __('Enter CMS version') ?></label>
                        <input type="text"
                               class="form-control <?= (isset($error['cms_version']) ? 'is-invalid' : '') ?>"
                               name="cms_version"
                               id="cms_version"
                               required
                               placeholder="<?= __('CMS version') ?>"
                        >
                    </div>
                    <div class="form-group">
                        <label for="status"><?= __('Enter status') ?></label>
                        <input type="text"
                               class="form-control <?= (isset($error['status']) ? 'is-invalid' : '') ?>"
                               name="status"
                               id="status"
                               required
                               placeholder="<?= __('Status') ?>"
                        >
                    </div>
                    <div class="form-group">
                        <label for="text"><?= __('Enter article text') ?></label>
                        <textarea class="form-control <?= (isset($error['text']) ? 'is-invalid' : '') ?>"
                                  name="text"
                                  id="text"
                                  rows="3"
                                  required
                                  placeholder="<?= __('Article text') ?>"></textarea>
                    </div>
                    <input type="hidden" name="parent_id" value="<?= $parent_id ?>">
                    <input type="hidden" name="author" value="<?= $user->id ?>">
                    <input type="hidden" name="date_of_creation" value="<?= (new DateTime())->getTimestamp() ?>">
                    <input type="submit" name="article_submit" class="btn btn-primary" value="<?= __('Add') ?>">
                </div>
            </form>

        </div>
    </div>
</div>
